const axios = require('axios');
const {faker} = require('@faker-js/faker');
const generateDummyData = async () => {
    for (let i = 0; i < 20; i++) {
        const name = faker.person.fullName();
        const post = `https://source.unsplash.com/random/?nature&${faker.number.int(30)}`; // Random photo from Unsplash with "avatar" query
        const description = faker.lorem.paragraph(1);
        const photo = `https://source.unsplash.com/random/?avatar&${faker.number.int(8)}`; // Random photo from Unsplash with "avatar" query
        const date = faker.date.past() || faker.date.recent();
        const likes = faker.number.int(100)
        const comments = [{
            comment: faker.lorem.paragraph(1), avatar: photo, name: faker.person.fullName(), date: faker.date.recent()
        }, {comment: faker.lorem.paragraph(1), avatar: photo, name: faker.person.fullName(), date: faker.date.past()}]

        const newData = {
            name, post, description, photo, date, likes,
        };

        const response = await axios.post('https://algo-bullls-default-rtdb.asia-southeast1.firebasedatabase.app/posts.json', newData);
        const postId = response.data.name;

        // Add comments to the post using the unique post ID generated by Firebase
        for (let j = 0; j < 2; j++) {
            const commentData = {
                comment: faker.lorem.paragraph(1),
                avatar: photo,
                name: faker.person.fullName(),
                date: faker.date.recent()
            };

            await axios.post(`https://algo-bullls-default-rtdb.asia-southeast1.firebasedatabase.app/posts/${postId}/comments.json`, commentData);
        }
    }

    console.log("Dummy data created successfully.");
};

generateDummyData();

